import makeWASocket,{DisconnectReason,useMultiFileAuthState} from "@whiskeysockets/baileys";
import type {WhatsAppConnector,WhatsAppConnection,WhatsAppStatus} from "./types.js";
export interface BaileysConnectorOptions{authDirectory:string;printQRInTerminal?:boolean;reconnectDelayMs?:number;}
type TextHandler=(message:{externalId:string;from:string;to:string;body:string})=>Promise<void>;
export function createBaileysConnector(o:BaileysConnectorOptions):WhatsAppConnector{
 let sock:ReturnType<typeof makeWASocket>|null=null;let status:WhatsAppStatus="disconnected";let phoneNumber:string|null=null;let qr:string|null=null;let qrUpdatedAt:string|null=null;let pairingCode:string|null=null;let pairingCodeUpdatedAt:string|null=null;let lastError:string|null=null;let closing=false;let connecting=false;let reconnectTimer:ReturnType<typeof setTimeout>|null=null;const handlers:TextHandler[]=[];
 const snapshot=():WhatsAppConnection=>({status,phoneNumber,qr,qrUpdatedAt,pairingCode,pairingCodeUpdatedAt,lastError});
 const scheduleReconnect=()=>{if(closing||reconnectTimer)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;void connect().catch(()=>{});},o.reconnectDelayMs??2000);};
 async function connect(){if(closing||connecting||status==="connected")return;connecting=true;status="connecting";lastError=null;try{const {state,saveCreds}=await useMultiFileAuthState(o.authDirectory);if(closing){connecting=false;return;}sock=makeWASocket({auth:state,printQRInTerminal:o.printQRInTerminal??false});sock.ev.on("creds.update",saveCreds);sock.ev.on("connection.update",({connection,lastDisconnect,qr:nextQr})=>{if(nextQr){qr=nextQr;qrUpdatedAt=new Date().toISOString();status="connecting";}if(connection==="open"){status="connected";phoneNumber=sock?.user?.id?.split(":")[0]??null;qr=null;qrUpdatedAt=null;pairingCode=null;pairingCodeUpdatedAt=null;lastError=null;}else if(connection==="close"){status="disconnected";phoneNumber=null;qr=null;pairingCode=null;pairingCodeUpdatedAt=null;const code=typeof lastDisconnect?.error==="object"&&lastDisconnect.error!==null&&"output"in lastDisconnect.error&&typeof(lastDisconnect.error as {output?:{statusCode?:unknown}}).output?.statusCode==="number"?(lastDisconnect.error as {output:{statusCode:number}}).output.statusCode:undefined;lastError=code?"connection_closed_"+code:"connection_closed";if(code!==DisconnectReason.loggedOut)scheduleReconnect();}});sock.ev.on("messages.upsert",async({messages,type,requestId})=>{if(type!=="notify"||requestId)return;for(const m of messages){if(m.key.fromMe||!m.message||!m.key.remoteJid)continue;const body=m.message.conversation??m.message.extendedTextMessage?.text;if(!body)continue;const msg={externalId:m.key.id??crypto.randomUUID(),from:m.key.remoteJid,to:sock?.user?.id??"",body};for(const h of handlers){try{await h(msg);}catch{lastError="message_handler_failed";}}}});}finally{connecting=false;}}
 return{connect,getConnection:snapshot,async requestPairingCode(input){const normalized=input.replace(/[^0-9]/g,"");if(normalized.length<8||normalized.length>15)throw new Error("invalid_phone_number");if(!sock||status!=="connecting")throw new Error("whatsapp_not_connecting");try{const code=await sock.requestPairingCode(normalized);pairingCode=code;pairingCodeUpdatedAt=new Date().toISOString();qr=null;qrUpdatedAt=null;lastError=null;return code;}catch(e){lastError="pairing_code_failed";throw e;}},async sendText(to,body){if(!sock||status!=="connected")throw new Error("whatsapp_not_connected");const m=await sock.sendMessage(to,{text:body});return{externalId:m?.key?.id??crypto.randomUUID()};},async onText(h){handlers.push(h);},async close(){closing=true;if(reconnectTimer){clearTimeout(reconnectTimer);reconnectTimer=null;}status="disconnected";qr=null;pairingCode=null;phoneNumber=null;if(sock){const current=sock;sock=null;await current.end(undefined);}}};
}