import type {FastifyInstance} from "fastify";
import type {AuthRepositories} from "../auth/types.js";import type {AuthorizationRepository} from "../auth/authorization-types.js";
import {createAuthGuard} from "../auth/auth-guard.js";import {createPermissionGuard} from "../auth/authorization-guard.js";
import type {ShipmentRepository,ShipmentStatus} from "../shipping/types.js";import {SHIPMENT_STATUSES} from "../shipping/types.js";
export interface AdminShippingOptions{deps:AuthRepositories;authorizationRepo:AuthorizationRepository;shipmentRepo:ShipmentRepository;tracker?:import("../shipping/types.js").ShipmentTracker;isProduction:boolean;}
function str(v:unknown){return typeof v==="string"&&v.trim()?v.trim():null;}
export async function adminShippingRoutes(app:FastifyInstance,o:AdminShippingOptions){const auth=createAuthGuard({...o.deps,isProduction:o.isProduction}),guard=createPermissionGuard(o.authorizationRepo,"shipping");
app.get("/orders/:orderId/shipping",{preHandler:[auth,guard]},async(req)=>o.shipmentRepo.getByOrderId((req.params as {orderId:string}).orderId));
app.put("/orders/:orderId/shipping",{preHandler:[auth,guard]},async(req,reply)=>{const orderId=(req.params as {orderId:string}).orderId,b=req.body&&typeof req.body==="object"?req.body as Record<string,unknown>:{},trackingUrl=b.trackingUrl===null?null:str(b.trackingUrl);try{return reply.send(await o.shipmentRepo.upsert({orderId,carrier:b.carrier===null?null:str(b.carrier),trackingCode:b.trackingCode===null?null:str(b.trackingCode),trackingUrl}));}catch(e){if(e instanceof Error&&e.message==="order_not_found")return reply.code(404).send({error:e.message});throw e;}});
app.post("/orders/:orderId/shipping/sync",{preHandler:[auth,guard]},async(req,reply)=>{if(!o.tracker)return reply.code(503).send({error:"tracking_provider_not_configured"});const orderId=(req.params as {orderId:string}).orderId;const shipment=await o.shipmentRepo.getByOrderId(orderId);if(!shipment||!shipment.carrier||!shipment.trackingCode)return reply.code(404).send({error:"tracking_data_not_found"});try{const result=await o.tracker.track({carrier:shipment.carrier,trackingCode:shipment.trackingCode});if(result.status===shipment.status)return reply.send(shipment);const updated=await o.shipmentRepo.setStatus(shipment.id,result.status);if(updated&&"error" in updated)return reply.code(409).send(updated);return reply.send(updated);}catch(e){if(e instanceof Error&&e.message==="tracking_provider_error")return reply.code(502).send({error:e.message});throw e;}});app.patch("/shipments/:id/status",{preHandler:[auth,guard]},async(req,reply)=>{const id=(req.params as {id:string}).id,b=req.body&&typeof req.body==="object"?req.body as Record<string,unknown>:{},status=b.status;if(typeof status!=="string"||!SHIPMENT_STATUSES.includes(status as ShipmentStatus))return reply.code(400).send({error:"invalid_status"});const r=await o.shipmentRepo.setStatus(id,status as ShipmentStatus);if(!r)return reply.code(404).send({error:"not_found"});if("error" in r)return reply.code(409).send(r);return reply.send(r);});}