import type {FastifyInstance} from "fastify";
import type {AuthRepositories} from "../auth/types.js";import type {AuthorizationRepository} from "../auth/authorization-types.js";
import {createAuthGuard} from "../auth/auth-guard.js";import {createPermissionGuard} from "../auth/authorization-guard.js";
import type {PaymentRepository,PaymentMethod,PaymentStatus} from "../payments/types.js";import {PAYMENT_METHODS,PAYMENT_STATUSES} from "../payments/types.js";
export interface AdminPaymentsOptions{deps:AuthRepositories;authorizationRepo:AuthorizationRepository;paymentRepo:PaymentRepository;isProduction:boolean;}
function str(v:unknown){return typeof v==="string"&&v.trim()?v.trim():null;}function amount(v:unknown):v is number{return typeof v==="number"&&Number.isInteger(v)&&v>0;}
export async function adminPaymentsRoutes(app:FastifyInstance,o:AdminPaymentsOptions){const auth=createAuthGuard({...o.deps,isProduction:o.isProduction}),guard=createPermissionGuard(o.authorizationRepo,"payments");
app.get("/orders/:orderId/payment",{preHandler:[auth,guard]},async(req)=>o.paymentRepo.getByOrderId((req.params as {orderId:string}).orderId));
app.put("/orders/:orderId/payment",{preHandler:[auth,guard]},async(req,reply)=>{const orderId=(req.params as {orderId:string}).orderId,b=req.body&&typeof req.body==="object"?req.body as Record<string,unknown>:{},method=b.method,amountValue=b.amount;if(typeof method!=="string"||!PAYMENT_METHODS.includes(method as PaymentMethod)||!amount(amountValue))return reply.code(400).send({error:"invalid_payment"});try{return reply.send(await o.paymentRepo.upsert({orderId,method:method as PaymentMethod,amount:amountValue,reference:b.reference===null?null:str(b.reference)}));}catch(e){if(e instanceof Error&&e.message==="order_not_found")return reply.code(404).send({error:e.message});throw e;}});
app.patch("/payments/:id/status",{preHandler:[auth,guard]},async(req,reply)=>{const id=(req.params as {id:string}).id,b=req.body&&typeof req.body==="object"?req.body as Record<string,unknown>:{},status=b.status;if(typeof status!=="string"||!PAYMENT_STATUSES.includes(status as PaymentStatus))return reply.code(400).send({error:"invalid_status"});if(status==="rejected"&&b.rejectionReason!==undefined&&!str(b.rejectionReason))return reply.code(400).send({error:"invalid_rejection_reason"});const r=await o.paymentRepo.setStatus(id,status as PaymentStatus,str(b.rejectionReason));if(!r)return reply.code(404).send({error:"not_found"});if("error" in r)return reply.code(409).send(r);return reply.send(r);});}