import type {FastifyInstance} from "fastify";
import type {AuthRepositories} from "../auth/types.js";
import {createAuthGuard} from "../auth/auth-guard.js";

export async function adminUiRoutes(app:FastifyInstance,o:{deps:AuthRepositories;isProduction:boolean}):Promise<void>{
 const auth=createAuthGuard({...o.deps,isProduction:o.isProduction});
 app.get("/login",async(_req,reply)=>reply.type("text/html; charset=utf-8").send(loginHtml()));
 app.get("/app",{preHandler:auth},async(_req,reply)=>reply.type("text/html; charset=utf-8").send(adminHtml()));
}
function shell(title:string,body:string,script:string){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#172033;background:#f4f6f9}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1280px;margin:auto;padding:20px}.top{background:#172033;color:white}.top .wrap{display:flex;justify-content:space-between;align-items:center;gap:16px}.brand{font-size:20px;font-weight:700}.muted{color:#697386}.top .muted{color:#cbd2df}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.nav button{border:1px solid #d7dce5;background:white;border-radius:8px;padding:9px 13px;cursor:pointer}.nav button.active{background:#172033;color:white}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.card{background:white;border:1px solid #e1e5ec;border-radius:12px;padding:16px;box-shadow:0 2px 8px #1720330d}.stat{font-size:28px;font-weight:700}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #e7eaf0;text-align:left;vertical-align:top}.table th{font-size:13px;color:#697386}.btn{border:0;border-radius:8px;padding:9px 13px;background:#172033;color:white;cursor:pointer}.btn.secondary{background:#e9edf3;color:#172033}.btn.danger{background:#a52828}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.field{display:flex;flex-direction:column;gap:5px;margin-bottom:10px}.field input,.field select,.field textarea{padding:9px;border:1px solid #cfd5df;border-radius:8px;font:inherit}.notice{padding:10px;border-radius:8px;background:#fff8dd;margin-bottom:12px}.hidden{display:none}.login{max-width:420px;margin:10vh auto}.error{color:#a52828;margin:8px 0}h1,h2{margin-top:0}@media(max-width:700px){.table{font-size:13px}.wrap{padding:12px}.top .wrap{align-items:flex-start;flex-direction:column}}
</style></head><body>${body}<script>${script}</script></body></html>`}

function loginHtml(){return shell("Admin Login",`<main class="wrap"><section class="card login"><h1>Admin</h1><p class="muted">Sign in to the commerce administration.</p><form id="login"><div class="field"><label>Email</label><input id="email" type="email" autocomplete="username" required></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password" required></div><div id="error" class="error"></div><button class="btn">Sign in</button></form></section></main>`,`document.querySelector("#login").addEventListener("submit",async e=>{e.preventDefault();const r=await fetch("/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:email.value,password:password.value})});if(r.ok)location.href="/admin/app";else document.querySelector("#error").textContent="Invalid credentials";});`)}

function adminHtml(){return shell("Commerce Admin",`<header class="top"><div class="wrap"><div><div class="brand">AI Commerce Admin</div><div class="muted" id="admin"></div></div><button class="btn secondary" id="logout">Logout</button></div></header><main class="wrap"><nav class="nav" id="nav"></nav><div id="notice"></div><section id="content"></section></main>`,`
const state={permissions:[],section:"dashboard",data:{}};
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,opt){const r=await fetch(path,opt);if(r.status===401){location.href="/admin/login";throw new Error("unauthorized")}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"request_failed");return d}
async function load(){const me=await api("/admin/me");$("#admin").textContent=me.admin.email;const dash=await api("/admin/dashboard").catch(()=>null);state.permissions=(dash?.permissions)||[];renderNav();show("dashboard")}
function renderNav(){const items=[["dashboard","Dashboard"],["products","Products"],["customers","Customers"],["orders","Orders"],["payments","Payments"],["shipping","Shipping"],["conversations","WhatsApp"],["ai","AI"]];$("#nav").innerHTML=items.filter(x=>x[0]==="dashboard"||state.permissions.includes(x[0])).map(x=>`<button data-s="${x[0]}" class="${state.section===x[0]?"active":""}">${x[1]}</button>`).join("");document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>show(b.dataset.s))}
async function show(section){state.section=section;renderNav();const c=$("#content");c.innerHTML="<div class='card'>Loading…</div>";try{if(section==="dashboard")return dashboard(c);if(section==="products")return products(c);if(section==="customers")return customers(c);if(section==="orders")return orders(c);if(section==="payments")return payments(c);if(section==="shipping")return shipping(c);if(section==="conversations")return whatsapp(c);if(section==="ai")return ai(c)}catch(e){c.innerHTML=`<div class="card error">${esc(e.message)}</div>`}}
function table(headers,rows){return `<div class="card"><table class="table"><thead><tr>${headers.map(h=>"<th>"+h+"</th>").join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`}
async function dashboard(c){const [p,o,cu]=await Promise.all([api("/admin/products"),api("/admin/orders"),api("/admin/customers")]);c.innerHTML=`<h1>Dashboard</h1><div class="grid"><div class="card"><div class="muted">Products</div><div class="stat">${p.length}</div></div><div class="card"><div class="muted">Customers</div><div class="stat">${cu.length}</div></div><div class="card"><div class="muted">Orders</div><div class="stat">${o.length}</div></div><div class="card"><div class="muted">Revenue</div><div class="stat">${o.reduce((n,x)=>n+x.total,0)}</div></div></div>`}
async function products(c){const p=await api("/admin/products");c.innerHTML="<h1>Products</h1>"+table(["Code","Name","Price","Active","Variants"],p.map(x=>`<tr><td>${esc(x.productCode)}</td><td>${esc(x.name)}</td><td>${esc(x.price)} ${esc(x.currency)}</td><td>${x.isActive?"Yes":"No"}</td><td>${x.variants.map(v=>esc(v.sku)+" ("+v.stockQuantity+")").join("<br>")}</td></tr>`))}
async function customers(c){const rows=await api("/admin/customers");c.innerHTML="<h1>Customers</h1>"+table(["Name","Phone","Email","Address"],rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.email)}</td><td>${esc(x.address)}</td></tr>`))}
async function orders(c){const rows=await api("/admin/orders");c.innerHTML="<h1>Orders</h1>"+table(["Order","Customer","Status","Total","Items"],rows.map(x=>`<tr><td>${esc(x.orderNumber)}</td><td>${esc(x.customerId)}</td><td><select data-id="${x.id}" class="order-status">${["received","review","preparing","shipped","on_the_way","cancelled"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></td><td>${esc(x.total)}</td><td>${x.items.length}</td></tr>`));document.querySelectorAll(".order-status").forEach(s=>s.onchange=async e=>{try{await api("/admin/orders/"+e.target.dataset.id+"/status",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:e.target.value})});show("orders")}catch(err){notice(err.message);}})}
async function payments(c){const rows=await api("/admin/orders");const out=[];for(const o of rows){const p=await api("/admin/orders/"+o.id+"/payment");if(p)out.push([o,p])}c.innerHTML="<h1>Payments</h1>"+table(["Order","Method","Amount","Status"],out.map(([o,p])=>`<tr><td>${esc(o.orderNumber)}</td><td>${esc(p.method)}</td><td>${esc(p.amount)}</td><td><select data-id="${p.id}" class="pay-status">${["pending","approved","rejected"].map(s=>`<option ${s===p.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`));document.querySelectorAll(".pay-status").forEach(s=>s.onchange=async e=>{await api("/admin/payments/"+e.target.dataset.id+"/status",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:e.target.value})});show("payments")})}
async function shipping(c){const rows=await api("/admin/orders");const out=[];for(const o of rows){const s=await api("/admin/orders/"+o.id+"/shipping");if(s)out.push([o,s])}c.innerHTML="<h1>Shipping</h1>"+table(["Order","Carrier","Tracking","Status"],out.map(([o,s])=>`<tr><td>${esc(o.orderNumber)}</td><td>${esc(s.carrier)}</td><td>${esc(s.trackingCode)}</td><td>${esc(s.status)}</td></tr>`))}
async function whatsapp(c){const s=await api("/admin/whatsapp/status");c.innerHTML=`<h1>WhatsApp</h1><div class="card"><p>Status: <strong>${esc(s.status)}</strong></p><p>Phone: ${esc(s.phoneNumber)}</p></div><div class="card"><h2>Send message</h2><form id="send"><div class="field"><label>Phone</label><input id="to" required></div><div class="field"><label>Message</label><textarea id="body" required></textarea></div><button class="btn">Send</button></form></div>`;$("#send").onsubmit=async e=>{e.preventDefault();await api("/admin/whatsapp/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({to:to.value,body:body.value})});e.target.reset();notice("Message sent")}}
async function ai(c){c.innerHTML=`<h1>AI Assistant</h1><div class="card"><form id="aif"><div class="field"><label>Message</label><textarea id="aim" rows="5" required placeholder="Ask about products, stock, or an order"></textarea></div><button class="btn">Ask AI</button></form><pre id="air"></pre></div>`;$("#aif").onsubmit=async e=>{e.preventDefault();$("#air").textContent="Working…";try{const r=await api("/admin/ai/respond",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:aim.value})});$("#air").textContent=r.reply}catch(err){$("#air").textContent=err.message}}}
function notice(x){$("#notice").innerHTML=`<div class="notice">${esc(x)}</div>`;setTimeout(()=>$("#notice").innerHTML="",3000)}
$("#logout").onclick=async()=>{await fetch("/admin/logout",{method:"POST"});location.href="/admin/login"};load().catch(e=>notice(e.message));
`)}
