import type {FastifyInstance} from "fastify";
import type {AuthRepositories} from "../auth/types.js";import type {AuthorizationRepository} from "../auth/authorization-types.js";
import {createAuthGuard} from "../auth/auth-guard.js";import {createPermissionGuard} from "../auth/authorization-guard.js";
import type {PaymentRepository,PaymentMethod,PaymentStatus} from "../payments/types.js";import {PAYMENT_METHODS,PAYMENT_STATUSES} from "../payments/types.js";
import type {MediaRepository} from "../catalog/media-types.js";import type {MediaStore} from "../storage/local-media-store.js";import type {ReceiptOcr} from "../payments/receipt-ocr.js";
const receiptTypes=new Map([["image/jpeg","jpg"],["image/png","png"],["image/webp","webp"]]);const maxReceiptBytes=10*1024*1024;
export interface AdminPaymentsOptions{deps:AuthRepositories;authorizationRepo:AuthorizationRepository;paymentRepo:PaymentRepository;mediaRepo:MediaRepository;mediaStore:MediaStore;receiptOcr:ReceiptOcr;isProduction:boolean;}
function str(v:unknown){return typeof v==="string"&&v.trim()?v.trim():null;}function amount(v:unknown):v is number{return typeof v==="number"&&Number.isInteger(v)&&v>0;}
export async function adminPaymentsRoutes(app:FastifyInstance,o:AdminPaymentsOptions){const auth=createAuthGuard({...o.deps,isProduction:o.isProduction}),guard=createPermissionGuard(o.authorizationRepo,"payments");
app.get("/orders/:orderId/payment",{preHandler:[auth,guard]},async(req)=>o.paymentRepo.getByOrderId((req.params as {orderId:string}).orderId));
app.get("/orders/:orderId/payment/receipts",{preHandler:[auth,guard]},async(req,reply)=>{const payment=await o.paymentRepo.getByOrderId((req.params as {orderId:string}).orderId);return payment?o.mediaRepo.list("payment_receipt",payment.id):reply.code(404).send({error:"payment_not_found"});});
app.put("/orders/:orderId/payment",{preHandler:[auth,guard]},async(req,reply)=>{const orderId=(req.params as {orderId:string}).orderId,b=req.body&&typeof req.body==="object"?req.body as Record<string,unknown>:{},method=b.method,amountValue=b.amount;if(typeof method!=="string"||!PAYMENT_METHODS.includes(method as PaymentMethod)||!amount(amountValue))return reply.code(400).send({error:"invalid_payment"});try{return reply.send(await o.paymentRepo.upsert({orderId,method:method as PaymentMethod,amount:amountValue,reference:b.reference===null?null:str(b.reference)}));}catch(e){if(e instanceof Error&&e.message==="order_not_found")return reply.code(404).send({error:e.message});throw e;}});
app.post("/orders/:orderId/payment/receipt",{preHandler:[auth,guard]},async(req,reply)=>{const orderId=(req.params as {orderId:string}).orderId;const payment=await o.paymentRepo.getByOrderId(orderId);if(!payment)return reply.code(404).send({error:"payment_not_found"});if(payment.method!=="bank_transfer")return reply.code(409).send({error:"receipt_not_supported_for_payment_method"});const q=req.query&&typeof req.query==="object"?req.query as Record<string,unknown>:{};const headerMime=typeof req.headers["x-media-content-type"]==="string"?req.headers["x-media-content-type"]:"";const mime=typeof q.contentType==="string"&&q.contentType.trim()?q.contentType.trim():headerMime;const extension=receiptTypes.get(mime);if(!extension)return reply.code(415).send({error:"unsupported_receipt_type"});const raw=Buffer.isBuffer(req.body)?req.body:null;if(!raw)return reply.code(400).send({error:"invalid_receipt_body"});if(raw.byteLength>maxReceiptBytes)return reply.code(413).send({error:"receipt_too_large"});const name=typeof q.filename==="string"&&q.filename.trim()?q.filename.trim():`receipt.${extension}`;try{const saved=await o.mediaStore.save({stream:raw,extension,maxBytes:maxReceiptBytes});let ocrText:string;try{ocrText=await o.receiptOcr.extract({buffer:raw,extension});}catch(e){await o.mediaStore.remove(saved.key);throw e;}return reply.code(201).send(await o.mediaRepo.create({ownerType:"payment_receipt",ownerId:payment.id,kind:"image",originalName:name,mimeType:mime,storageKey:saved.key,sizeBytes:saved.sizeBytes,ocrText}));}catch(e){if(e instanceof Error&&e.message==="receipt_ocr_failed")return reply.code(422).send({error:e.message});throw e;}});
app.patch("/payments/:id/status",{preHandler:[auth,guard]},async(req,reply)=>{const id=(req.params as {id:string}).id,b=req.body&&typeof req.body==="object"?req.body as Record<string,unknown>:{},status=b.status;if(typeof status!=="string"||!PAYMENT_STATUSES.includes(status as PaymentStatus))return reply.code(400).send({error:"invalid_status"});if(status==="rejected"&&b.rejectionReason!==undefined&&!str(b.rejectionReason))return reply.code(400).send({error:"invalid_rejection_reason"});const r=await o.paymentRepo.setStatus(id,status as PaymentStatus,str(b.rejectionReason));if(!r)return reply.code(404).send({error:"not_found"});if("error" in r)return reply.code(409).send(r);return reply.send(r);});}