/* eslint-disable @typescript-eslint/no-explicit-any */
import type { PrismaClient } from "../../generated/prisma/client.js";
import type { ProductRepository, ProductRecord, ProductVariantRecord } from "./types.js";
type ProductRow={id:string;name:string;description:string|null;productCode:string;price:number;cost:number|null;currency:string;isActive:boolean;categoryId:string|null;createdAt:Date;updatedAt:Date;variants:Array<{id:string;productId:string;sku:string;size:string|null;color:string|null;stockQuantity:number;priceOverride:number|null}>};
function mapProduct(row:ProductRow):ProductRecord&{variants:ProductVariantRecord[]}{return {id:row.id,name:row.name,description:row.description,productCode:row.productCode,price:Number(row.price),cost:row.cost===null?null:Number(row.cost),currency:row.currency,isActive:row.isActive,categoryId:row.categoryId,createdAt:row.createdAt,updatedAt:row.updatedAt,variants:row.variants.map(v=>({id:v.id,productId:v.productId,sku:v.sku,size:v.size,color:v.color,stockQuantity:v.stockQuantity,priceOverride:v.priceOverride===null?null:Number(v.priceOverride)}))};}
function code(e:unknown){return typeof e==="object"&&e!==null&&"code" in e&&typeof e.code==="string"?e.code:undefined;}
function target(e:unknown){if(typeof e!=="object"||e===null||!("meta" in e))return "";const m=(e as any).meta;return m&&typeof m==="object"&&"target" in m?String(m.target):"";}
export function createPrismaProductRepository(prisma:PrismaClient):ProductRepository{return{
 async list(){const rows=await prisma.product.findMany({orderBy:{createdAt:"desc"},include:{variants:{orderBy:{sku:"asc"}}}});return rows.map(r=>mapProduct(r as ProductRow));},
 async create(input){try{const row=await prisma.product.create({data:{name:input.name,description:input.description??null,productCode:input.productCode,price:input.price,cost:input.cost??null,currency:input.currency,isActive:true,categoryId:input.categoryId??null,variants:{create:input.variants?.map(v=>({sku:v.sku,size:v.size??null,color:v.color??null,stockQuantity:v.stockQuantity,priceOverride:v.priceOverride??null}))??[]}},include:{variants:true}});return mapProduct(row as any);}catch(e){if(code(e)==="P2002")throw new Error(target(e).includes("sku")?"variant_sku_conflict":"product_code_conflict",{cause:e});if(code(e)==="P2003")throw new Error("category_not_found",{cause:e});throw e;}},
 async update(id,input){try{return mapProduct(await prisma.product.update({where:{id},data:input,include:{variants:true}}) as any);}catch(e){if(code(e)==="P2025")return null;if(code(e)==="P2002")throw new Error("product_code_conflict",{cause:e});if(code(e)==="P2003")throw new Error("category_not_found",{cause:e});throw e;}},
 async setVariantStock(productId,variantId,stockQuantity){const result=await prisma.productVariant.updateMany({where:{id:variantId,productId},data:{stockQuantity}});if(!result.count)return null;const row=await prisma.productVariant.findUnique({where:{id:variantId}});return row?{id:row.id,productId:row.productId,sku:row.sku,size:row.size,color:row.color,stockQuantity:row.stockQuantity,priceOverride:row.priceOverride===null?null:Number(row.priceOverride)}:null;}
};}
