import type {ConversationRepository,ConversationRecord,ConversationMessageRecord} from "./types.js";
export function createInMemoryConversationRepository():ConversationRepository{const cs:ConversationRecord[]=[];const ms:ConversationMessageRecord[]=[];let n=0;return{
 async getOrCreate(externalId,customerId=null){let c=cs.find(x=>x.externalId===externalId);if(!c){const now=new Date();c={id:"conv-"+(++n),externalId,customerId,channel:"whatsapp",status:"open",assignedAdminUserId:null,handoffReason:null,summary:null,summaryUpdatedAt:null,lastMessageAt:null,createdAt:now,updatedAt:now};cs.push(c);}else if(customerId)c.customerId=customerId;return c;},
 async addMessage(i){if(ms.some(x=>x.externalId===i.externalId))return ms.find(x=>x.externalId===i.externalId)!;const m={id:"msg-"+(++n),conversationId:i.conversationId,externalId:i.externalId,direction:i.direction,messageType:i.messageType??"text",body:i.body??null,fromAddress:i.fromAddress??null,toAddress:i.toAddress??null,createdAt:new Date()};ms.push(m);const c=cs.find(x=>x.id===i.conversationId);if(c){c.lastMessageAt=m.createdAt;c.updatedAt=m.createdAt;}return m;},
 async listMessages(id,limit){return ms.filter(x=>x.conversationId===id).sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()).slice(0,Math.min(Math.max(limit,1),200));},
 async list(status){return cs.filter(x=>!status||x.status===status).sort((a,b)=>(b.lastMessageAt?.getTime()??0)-(a.lastMessageAt?.getTime()??0));},
 async setStatus(id,status,assignedAdminUserId=null,handoffReason=null){const c=cs.find(x=>x.id===id);if(!c)return null;c.status=status;c.assignedAdminUserId=assignedAdminUserId;c.handoffReason=handoffReason;c.updatedAt=new Date();return c;},
 async setSummary(id,summary){const c=cs.find(x=>x.id===id);if(!c)return null;c.summary=summary;c.summaryUpdatedAt=summary?new Date():null;c.updatedAt=new Date();return c;},
 async getContext(id,limit){const c=cs.find(x=>x.id===id);if(!c)return null;return{conversation:c,messages:await this.listMessages(id,limit)};}
};}
