import {randomUUID} from "node:crypto";
import type {AiToolDefinition} from "./types.js";
import type {ProductRepository} from "../catalog/types.js";
import type {OrderRepository} from "../orders/types.js";
import type {PaymentRepository} from "../payments/types.js";
import type {ShipmentRepository} from "../shipping/types.js";
const text=(x:unknown)=>typeof x==="string"?x.trim():"";
const positiveInt=(x:unknown)=>typeof x==="number"&&Number.isInteger(x)&&x>0;
export function createCommerceTools(r:{products:ProductRepository;orders:OrderRepository;payments:PaymentRepository;shipping:ShipmentRepository;customerId?:string;canCreateOrder?:boolean}):AiToolDefinition[]{const tools:AiToolDefinition[]=[
{name:"search_products",description:"Search active catalog products. Returned price, variants, sizes, colors, and stock are authoritative. Never infer unavailable variants.",inputSchema:{type:"object",properties:{query:{type:"string"}}},execute:async a=>{const q=text(a.query).toLowerCase();const rows=await r.products.list();return rows.filter(p=>p.isActive&&(q===""||p.name.toLowerCase().includes(q)||p.productCode.toLowerCase().includes(q)||p.variants.some(v=>v.sku.toLowerCase().includes(q)||String(v.size??"").toLowerCase().includes(q)||String(v.color??"").toLowerCase().includes(q)))).slice(0,20).map(p=>({id:p.id,name:p.name,productCode:p.productCode,price:p.price,currency:p.currency,variants:p.variants.map(v=>({id:v.id,sku:v.sku,size:v.size,color:v.color,stockQuantity:v.stockQuantity,price:v.priceOverride??p.price}))}));}},
{name:"get_product",description:"Read one product by id, product code, or SKU. Use this before answering exact product facts.",inputSchema:{type:"object",properties:{productId:{type:"string"},productCode:{type:"string"},sku:{type:"string"}}},execute:async a=>{const id=text(a.productId),code=text(a.productCode).toLowerCase(),sku=text(a.sku).toLowerCase();const row=(await r.products.list()).find(p=>p.id===id||p.productCode.toLowerCase()===code||p.variants.some(v=>v.sku.toLowerCase()===sku));if(!row)return{found:false};return{found:true,id:row.id,name:row.name,description:row.description,productCode:row.productCode,price:row.price,currency:row.currency,variants:row.variants.map(v=>({id:v.id,sku:v.sku,size:v.size,color:v.color,stockQuantity:v.stockQuantity,price:v.priceOverride??row.price}))};}},
{name:"check_stock",description:"Check current stock for a product variant. Never estimate stock.",inputSchema:{type:"object",properties:{variantId:{type:"string"},sku:{type:"string"}}},execute:async a=>{const variantId=text(a.variantId),sku=text(a.sku).toLowerCase();for(const p of await r.products.list()){const v=p.variants.find(x=>x.id===variantId||x.sku.toLowerCase()===sku);if(v)return{found:true,productId:p.id,productName:p.name,sku:v.sku,size:v.size,color:v.color,stockQuantity:v.stockQuantity,available:v.stockQuantity>0};}return{found:false};}},
{name:"get_order_status",description:"Read the customer's current order status. Never infer it from conversation text.",inputSchema:{type:"object",properties:{orderId:{type:"string"}}},execute:async a=>{const id=text(a.orderId);const order=(await r.orders.list()).find(x=>x.id===id||x.orderNumber===id);if(!order)return{found:false};if(r.customerId&&order.customerId!==r.customerId)return{found:false};return{found:true,id:order.id,orderNumber:order.orderNumber,status:order.status,createdAt:order.createdAt,updatedAt:order.updatedAt,items:order.items.map(x=>({productName:x.productName,sku:x.sku,size:x.size,color:x.color,quantity:x.quantity,unitPrice:x.unitPrice})),total:order.total};}},
{name:"get_payment_status",description:"Read the current payment status for a customer's order. A submitted receipt is not proof of approval.",inputSchema:{type:"object",properties:{orderId:{type:"string"}}},execute:async a=>{const id=text(a.orderId);const order=(await r.orders.list()).find(x=>x.id===id||x.orderNumber===id);if(!order||r.customerId&&order.customerId!==r.customerId)return{found:false};return{found:true,payment:await r.payments.getByOrderId(order.id)};}},
{name:"get_shipping_status",description:"Read the current shipping status and tracking data for a customer's order. Never invent tracking data.",inputSchema:{type:"object",properties:{orderId:{type:"string"}}},execute:async a=>{const id=text(a.orderId);const order=(await r.orders.list()).find(x=>x.id===id||x.orderNumber===id);if(!order||r.customerId&&order.customerId!==r.customerId)return{found:false};return{found:true,shipment:await r.shipping.getByOrderId(order.id)};}}
];if(r.canCreateOrder){tools.push({name:"create_order",description:"Create an order only after the customer has explicitly confirmed the exact products, variants, quantities, and order intent. Stock is checked and decremented transactionally by the order repository.",inputSchema:{type:"object",properties:{confirmed:{type:"boolean"},items:{type:"array",items:{type:"object",properties:{productId:{type:"string"},variantId:{type:"string"},quantity:{type:"integer",minimum:1}},required:["productId","variantId","quantity"]}}},required:["confirmed","items"]},execute:async a=>{if(a.confirmed!==true)return{created:false,error:"explicit_confirmation_required"};if(!r.customerId)return{created:false,error:"customer_context_required"};if(!Array.isArray(a.items)||!a.items.length)return{created:false,error:"items_required"};const items=a.items.map(x=>{const v=x as Record<string,unknown>;if(typeof v.productId!=="string"||typeof v.variantId!=="string"||!positiveInt(v.quantity))throw new Error("invalid_order_items");return{productId:v.productId,variantId:v.variantId,quantity:v.quantity};});const orderNumber="AI-"+new Date().toISOString().replace(/\\D/g,"").slice(0,14)+"-"+randomUUID().slice(0,6).toUpperCase();try{const order=await r.orders.create({orderNumber,customerId:r.customerId,items});return{created:true,orderId:order.id,orderNumber:order.orderNumber,status:order.status,total:order.total};}catch(e){return{created:false,error:e instanceof Error?e.message:"order_creation_failed"};}}});}return tools;}
