import {describe,it,expect} from "vitest";
import Fastify from "fastify";
import {adminOrdersRoutes} from "../../src/routes/admin-orders.js";
import {createFakeAuthRepositories} from "../helpers/fake-repositories.js";
import {generateSessionToken,hashSessionToken} from "../../src/auth/session-token.js";
import type {AuthorizationRepository} from "../../src/auth/authorization-types.js";
import {createInMemoryCustomerRepository} from "../../src/customers/in-memory-customer-repository.js";
import {createInMemoryProductRepository} from "../../src/catalog/in-memory-product-repository.js";
import {createInMemoryOrderRepository} from "../../src/orders/in-memory-order-repository.js";
async function setup(perms:string[]){const app=Fastify(),auth=createFakeAuthRepositories([{id:"a1",email:"o@example.com",passwordHash:"x",isActive:true}]),token=generateSessionToken();await auth.adminSessionRepo.create({adminUserId:"a1",tokenHash:hashSessionToken(token),expiresAt:new Date(Date.now()+60000)});const authorizationRepo:AuthorizationRepository={async getPermissionKeysForAdmin(){return [...perms] as never;}};const customers=createInMemoryCustomerRepository(),products=createInMemoryProductRepository();const customer=await customers.create({name:"Ali",phone:"+905551112233"});const product=await products.create({name:"Shirt",productCode:"SH-1",price:1200,currency:"TRY",variants:[{sku:"SH-1-M",size:"M",color:"Black",stockQuantity:4,priceOverride:null}]});await app.register(adminOrdersRoutes,{deps:auth,authorizationRepo,orderRepo:createInMemoryOrderRepository(customers,products),isProduction:false});return{app,token,customer,product};}
describe("admin orders",()=>{it("requires orders permission",async()=>{const x=await setup([]);const r=await x.app.inject({method:"GET",url:"/orders",headers:{cookie:"admin_session="+x.token}});expect(r.statusCode).toBe(403);await x.app.close();});
it("creates an order with snapshots and total",async()=>{const x=await setup(["orders"]);const r=await x.app.inject({method:"POST",url:"/orders",headers:{cookie:"admin_session="+x.token},payload:{customerId:x.customer.id,items:[{productId:x.product.id,variantId:x.product.variants[0]!.id,quantity:2}]}});expect(r.statusCode).toBe(201);expect(r.json().status).toBe("received");expect(r.json().items[0].unitPrice).toBe(1200);expect(r.json().total).toBe(2400);await x.app.close();});
it("allows cancellation before shipping but rejects it after shipping",async()=>{const x=await setup(["orders"]);const create=await x.app.inject({method:"POST",url:"/orders",headers:{cookie:"admin_session="+x.token},payload:{customerId:x.customer.id,items:[{productId:x.product.id,quantity:1}]}});const id=create.json().id;let r=await x.app.inject({method:"PATCH",url:"/orders/"+id+"/status",headers:{cookie:"admin_session="+x.token},payload:{status:"cancelled"}});expect(r.statusCode).toBe(200);const create2=await x.app.inject({method:"POST",url:"/orders",headers:{cookie:"admin_session="+x.token},payload:{customerId:x.customer.id,items:[{productId:x.product.id,quantity:1}]}});for(const status of ["review","preparing","shipped"]){r=await x.app.inject({method:"PATCH",url:"/orders/"+create2.json().id+"/status",headers:{cookie:"admin_session="+x.token},payload:{status}});expect(r.statusCode).toBe(200);}r=await x.app.inject({method:"PATCH",url:"/orders/"+create2.json().id+"/status",headers:{cookie:"admin_session="+x.token},payload:{status:"cancelled"}});expect(r.statusCode).toBe(409);await x.app.close();});});